name: Linux

on:
  push:
    branches:
      - master

jobs:
  qt5:
    name: DQ Viewer (Qt5)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qt5-qmake libvlc-dev
      - name: Configure build
        run: qmake dqview.pro
      - name: Build project
        run: make -j2

  qt6:
    name: DQ Viewer (Qt6)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qt6-base-dev libvlc-dev
      - name: Configure build
        run: qmake6 dqview.pro
      - name: Build project
        run: make -j2
