name: RPM
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build RPM package
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "dqview.spec"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DQView.rpm
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
