name: OS X

on:
  push:
    branches:
      - master

jobs:
  build:
    name: DQView
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install msys2
        uses: msys2/setup-msys2@v2
      - name: Install msys2 packages
        - shell: msys2 {0}
          run: pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5-base mingw-w64-x86_64-vlc
      - name: Build project
        - shell: msys2 {0}
          run: |
            qmake dqview.pro
            make
      - name: Create installer
        - shell: msys2 {0}
          run: makensis.exe dqview.nsi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: DQView-*.exe
