name: Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    name: DQ Viewer
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-tools-git mingw-w64-x86_64-qt5-base mingw-w64-x86_64-vlc mingw-w64-x86_64-nsis
      - name: Build project
        run: |
          qmake dqview.pro
          make -j4
      - name: Create installer
        run: |
          cp release/dqview.exe .
          cp -r /mingw64/share/qt5/plugins/platforms platforms
          cp -r /mingw64/share/qt5/plugins/styles styles

          scripts/libs.sh

          makensis.exe dqview.nsi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: DQView-*.exe
          name: DQView.exe
          compression-level: 0
